### PR TITLE
Request improvements

### PR DESCRIPTION
**Pull request by mkrajewski90**
Some request improvements.

### CODE REVIEW

**Comment by mkrajewski90** [comment]
@bluszcz - some tests in the last commit :)

**Comment by bluszcz** [comment]
> @bluszcz - some tests in the last commit :)

Sweet. Let me go through it today! <3

**Comment by bluszcz** [comment]
```
Finished in 0.0620244 seconds.
--------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------
9 tests, 12 assertions, 0 failures, 0 errors, 0 pendings, 0 omissions, 0 notifications
100% passed
--------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------
145.10 tests/s, 193.47 assertions/s
```
Nice. Today will finish the review.

**Comment by bluszcz** [comment]
I am getting this during `rake` - do you have any idea why, by any chance?

```
........Error reading file /tmp/jekyll-strapi-src/_layouts/post.html: No such file or directory @ rb_sysopen - /tmp/jekyll-strapi-src/_layouts/post.html
```

**Comment by mkrajewski90** [comment]
Fixed on the last commit :) 

The issue was in config directory setup. By the way - your UT config might also load directory in a similar way.

**Comment by bluszcz** [comment]
Thank you, that's great contribution <3

**Pull request merged**
